# Generated by Django 2.2.5 on 2019-09-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190902_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cedula',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='user',
            name='telefono',
            field=models.DecimalField(decimal_places=0, max_digits=11),
        ),
    ]
